default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dev_link_shortener

test:
  <<: *default
  database: test_link_shortener

production:
  <<: *default
  database: prod_link_shortener